###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Cook, CS165
# Author:
#     Aaron Shiffler
# Summary:
#     This provides a collection of classes than can be populated
#     with informtion and that info can be drawn upon through the
#     other classes and the main program. It is a library of tools
#     that can be used and reused in many use-cases. 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

