###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Cook, CS165
# Author:
#     Aaron Shiffler
# Summary:
#     Allow a user to declare a product and view details about
#     it in different structures.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

