###############################################################
# Program:
#     Checkpoint 06a, Makefiles
#     Brother Cook, CS165
# Author:
#     Aaron Shiffler
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


# Insert your rule for a.out here:
all: robot.o point.o check06a.o
	g++ robot.o point.o check06a.o
# Insert your rule for robot.o here:
robot.o: robot.cpp
	g++ -c robot.cpp
# Insert your rule for point.o here:
point.o: point.cpp
	g++ -c point.cpp
# Insert your rule for check06a.o here:
check06a.o: check06a.cpp
	g++ -c check06a.cpp
